import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  Archive,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  Brain,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  Contact,
  CreditCard,
  Crosshair,
  Database,
  FileText,
  Filter,
  Gauge,
  GitBranch,
  Inbox,
  KeyRound,
  Layers,
  LifeBuoy,
  Link2,
  ListChecks,
  Mail,
  MessageCircle,
  Network,
  Plane,
  Radar,
  Radio,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Swords,
  Target,
  Trash2,
  TrendingUp,
  Users,
  Webhook,
  Workflow,
  Zap,
} from "lucide-react";

export type NavStatus = "live" | "planned";

export type NavItem = {
  /** Stable key, also used as the route segment. */
  key: string;
  label: string;
  href: string;
  icon: LucideIcon;
  status: NavStatus;
  /** Implementation phase from the build plan — shown on planned screens. */
  phase: string;
  /** What this screen is for. Used by the command palette and stub pages. */
  purpose: string;
  /** Planned scope, listed on stub pages so nothing looks silently broken. */
  planned?: string[];
  /** Which badge counter to render, if any. */
  counter?: "inbox" | "queue" | "approvals" | "notifications" | "autopilot";
  /** Extra command-palette search terms. */
  keywords?: string[];
};

export type NavGroup = { key: string; label: string; items: NavItem[] };

export const NAV: NavGroup[] = [
  {
    key: "workspace",
    label: "Workspace",
    items: [
      {
        key: "today",
        label: "Today",
        href: "/today",
        icon: Gauge,
        status: "live",
        phase: "Phase 2",
        purpose: "Your morning command centre: what changed, who to contact, what needs you.",
        keywords: ["home", "dashboard", "brief", "morning", "mission control"],
      },
      {
        key: "leads",
        label: "Leads",
        href: "/leads",
        icon: Target,
        status: "live",
        phase: "Phase 2",
        purpose: "The central lead database with scoring, intent and filters.",
        keywords: ["prospects", "contacts", "people", "database"],
      },
      { key: "opportunities", label: "Opportunities", href: "/opportunities", icon: Target, status: "live", phase: "Opportunity intelligence", purpose: "Source-backed requirements, evidence and change history." },
      {
        key: "find-leads",
        label: "Find Opportunities",
        href: "/find-leads",
        icon: ScanSearch,
        status: "live",
        phase: "Phase 5",
        purpose: "Describe who you sell to in plain language, or bring your own list.",
        keywords: ["icp", "search", "prospecting", "discover"],
      },
      {
        key: "pipeline",
        label: "Pipeline",
        href: "/pipeline",
        icon: GitBranch,
        status: "live",
        phase: "Phase 3",
        purpose: "Drag-and-drop deal board with stage value, ageing and risk flags.",
        keywords: ["deals", "kanban", "board", "opportunities", "forecast"],
      },
      {
        key: "teamcollab",
        label: "TeamCollab",
        href: "/teamcollab",
        icon: Users,
        status: "live",
        phase: "Phase 3",
        purpose: "Turn big opportunities into coordinated team work rather than lone CRM records.",
        planned: [
          "@-mentions and threaded replies on a note",
          "Attaching a note to a deal or company, not only a lead",
        ],
        keywords: ["team", "collaborate", "roadmap", "orchestration", "projects"],
      },
      {
        key: "my-queue",
        label: "My Queue",
        href: "/my-queue",
        icon: ListChecks,
        status: "live",
        phase: "Phase 3",
        purpose: "Your personal execution list, ranked by business impact rather than due date.",
        counter: "queue",
        keywords: ["tasks", "todo", "focus", "work"],
      },
      {
        key: "inbox",
        label: "Inbox",
        href: "/inbox",
        icon: Inbox,
        status: "live",
        phase: "Phase 4",
        purpose: "One thread list across email, WhatsApp and LinkedIn with lead context alongside.",
        planned: [
          "AI summarise, draft reply and detect objection",
          "Book a meeting from the thread",
        ],
        counter: "inbox",
        keywords: ["email", "messages", "replies", "conversations"],
      },
      {
        key: "outreach",
        label: "Outreach",
        href: "/outreach",
        icon: Send,
        status: "live",
        phase: "Phase 4",
        purpose: "Multi-step, multi-channel sequences with deliverability guardrails.",
        // Only what is still missing. The builder, the stop conditions, the
        // send windows and the caps are built and enforced by the engine.
        planned: [
          "Deliverability dashboard: bounce rate, sender reputation, domain health",
          "Transport for every channel — steps of any channel can be built and are queued by the engine, but no provider is connected to deliver them",
          "A/B testing across step variants",
        ],
        keywords: ["sequences", "campaigns", "cadence", "drip"],
      },
      {
        key: "autopilot",
        label: "Autopilot",
        href: "/autopilot",
        icon: Plane,
        status: "live",
        phase: "Phase 8",
        purpose: "The limits agents work inside — who they may touch, what they may spend, and what a person must approve first.",
        planned: [
          "Agents that actually run — needs a model provider connected",
          "Per-agent tool implementations beyond the read-only set",
          "A learning loop that tightens the limits from what you approve and overrule",
        ],
        counter: "autopilot",
        keywords: ["automation", "agent", "auto", "robot"],
      },
      {
        key: "whatsapp",
        label: "WhatsApp",
        href: "/whatsapp",
        icon: MessageCircle,
        status: "live",
        phase: "Phase 4",
        purpose: "India-first messaging via the official WhatsApp Business API.",
        planned: [
          "Template catalogue sync and approval status — templates are sent by name today",
          "Personal WhatsApp pairing — only the official Business Cloud API is supported",
        ],
        keywords: ["wa", "chat", "messaging"],
      },
      {
        key: "linkedin",
        label: "LinkedIn",
        href: "/linkedin",
        icon: Contact,
        status: "live",
        phase: "Phase 4",
        purpose: "Policy-compliant assisted workflows — no hidden browser automation.",
        planned: [
          "A drafting helper for the message you then send yourself",
          "Queued manual actions that appear in My Queue",
        ],
        keywords: ["li", "social", "connect"],
      },
      {
        key: "proposals",
        label: "Proposals",
        href: "/proposals",
        icon: FileText,
        status: "live",
        phase: "Phase 7",
        purpose: "Proposals a customer reads on a private link, with real view tracking and acceptance.",
        planned: [
          "AI drafting from the lead's research and past won proposals",
          "E-signature and a countersigned copy",
          "Payment collection against an accepted proposal",
        ],
        keywords: ["quote", "sow", "pricing", "estimate"],
      },
      {
        key: "bookings",
        label: "Bookings",
        href: "/bookings",
        icon: CalendarClock,
        status: "live",
        phase: "Phase 7",
        purpose: "Meetings recorded against the lead, with the pre-call brief that makes the call land and the outcome that moves the deal.",
        planned: [
          "A public booking page with real availability",
          "Call recording, transcription and automatic outcome capture",
        ],
        keywords: ["meetings", "calendar", "schedule", "calls"],
      },
    ],
  },
  {
    key: "intelligence",
    label: "Intelligence",
    items: [
      {
        key: "lead-lens",
        label: "Lead Lens",
        href: "/lead-lens",
        icon: ScanSearch,
        status: "live",
        phase: "Phase 5",
        purpose: "Paste a name, LinkedIn URL or company and get a full dossier on demand.",
        planned: [
          "Pasting a job advert or a news article and extracting the company",
        ],
        keywords: ["lookup", "enrich", "research one"],
      },
      {
        key: "people-finder",
        label: "People Finder",
        href: "/people-finder",
        icon: Search,
        status: "live",
        phase: "Phase 5",
        purpose: "Database-style search across roles, seniority, industry and intent.",
        planned: [
          "Searching beyond your own data — needs a licensed people database",
          "Saving a search as a list",
        ],
        keywords: ["search people", "database", "prospect search"],
      },
      {
        key: "live-demand",
        label: "Live Demand",
        href: "/live-demand",
        icon: Radio,
        status: "live",
        phase: "Phase 5",
        purpose: "Buyer signals aggregated into opportunity categories you can act on.",
        planned: [
          "New signals arriving — needs a discovery source connected",
          "Acting on a category in bulk",
        ],
        keywords: ["demand", "trends", "market", "index"],
      },
      {
        key: "lists",
        label: "Lists",
        href: "/lists",
        icon: Layers,
        status: "live",
        phase: "Phase 5",
        purpose: "Static and smart lists that keep themselves up to date from saved filters.",
        planned: [
          "Adding leads to a static list from the Leads screen in bulk",
          "Sharing a list with a colleague",
        ],
        keywords: ["segments", "groups", "collections"],
      },
      {
        key: "saved-alerts",
        label: "Saved & Alerts",
        href: "/saved-alerts",
        icon: Bell,
        status: "live",
        phase: "Phase 5",
        purpose: "Save any search and get told when new matches appear.",
        planned: [
          "Alerts that fire on new matches — needs a discovery source connected",
          "Saving searches on surfaces other than Leads",
        ],
        keywords: ["saved searches", "notifications", "watch"],
      },
      {
        key: "insights",
        label: "Insights",
        href: "/insights",
        icon: BarChart3,
        status: "live",
        phase: "Phase 5",
        purpose: "The funnel from signal to revenue, and which sources actually produce money.",
        planned: [
          "Cohort analysis, so the funnel follows one group through",
          "Forecast accuracy against what was actually committed",
        ],
        keywords: ["analytics", "reports", "funnel", "attribution", "metrics"],
      },
      {
        key: "radar",
        label: "Radar",
        href: "/radar",
        icon: Radar,
        status: "live",
        phase: "Phase 5",
        purpose: "Continuous monitoring of people, accounts, keywords and technologies.",
        planned: [
          "Watches that actually fire — needs a discovery source connected",
          "Watching a person's job change across companies",
        ],
        keywords: ["monitor", "watch", "tracking"],
      },
      {
        key: "accounts",
        label: "Accounts",
        href: "/accounts",
        icon: Building2,
        status: "live",
        phase: "Phase 5",
        purpose: "Company-level intelligence, including the buying committee map.",
        planned: [
          "Org-chart view of the committee with reporting lines",
          "Account plans with a named strategy per account",
        ],
        keywords: ["companies", "organisations", "abm"],
      },
      {
        key: "competitors",
        label: "Competitors",
        href: "/competitors",
        icon: Swords,
        status: "live",
        phase: "Phase 5",
        purpose: "Public signals about switching, dissatisfaction and comparison.",
        planned: [
          "Win/loss analysis against each named competitor",
          "Battlecards drawn from what prospects actually said",
        ],
        keywords: ["rivals", "displacement", "win-loss"],
      },
      {
        key: "market-intelligence",
        label: "Market Intelligence",
        href: "/market-intelligence",
        icon: TrendingUp,
        status: "live",
        phase: "Phase 5",
        purpose: "Sector-level movement across the industries and cities you sell into.",
        planned: [
          "Comparison against the market rather than your own pipeline",
          "Movement over time, not just a current snapshot",
        ],
        keywords: ["market", "sector", "industry trends"],
      },
      {
        key: "team",
        label: "Team",
        href: "/team",
        icon: Users,
        status: "live",
        phase: "Phase 5",
        purpose: "Team activity and conversion, including who is busy but not converting.",
        planned: [
          "Per-person coaching notes tied to the numbers",
          "Activity heatmaps by hour and day",
        ],
        keywords: ["reps", "performance", "leaderboard"],
      },
    ],
  },
  {
    key: "ai",
    label: "AI",
    items: [
      {
        key: "copilot",
        label: "Copilot",
        href: "/copilot",
        icon: Sparkles,
        status: "live",
        phase: "Phase 6",
        purpose: "Ask anything about your workspace and get an answer read from real tools.",
        planned: [
          "Acting from the Copilot — today it reads, and writes go through Agents",
          "Research, drafting and sending, once those four tools are built",
        ],
        keywords: ["chat", "assistant", "ask", "ai"],
      },
      {
        key: "research",
        label: "Research",
        href: "/research",
        icon: Brain,
        status: "live",
        phase: "Phase 6",
        purpose: "What you already know about an account, every line citing its record.",
        planned: [
          "Deep external research — needs a licensed data source and a model provider",
          "Outreach angles derived from the dossier, once drafting is wired",
        ],
        keywords: ["dossier", "deep research", "enrichment"],
      },
      {
        key: "playbooks",
        label: "Playbooks",
        href: "/playbooks",
        icon: Workflow,
        status: "live",
        phase: "Phase 6",
        purpose: "Codify what works: trigger conditions plus the sequence of steps to run.",
        planned: [
          "Executing a playbook — the steps are defined and checked, not yet run",
          "A step editor; today steps are resolved and shown, and edited via the API",
        ],
        keywords: ["automation", "recipes", "workflows"],
      },
      {
        key: "ai-agents",
        label: "AI Agents",
        href: "/ai-agents",
        icon: Bot,
        status: "live",
        phase: "Phase 8",
        purpose: "Specialised agents, each with its own goals, tools, budget and approval policy.",
        planned: [
          "Agents that actually run — needs a model provider connected",
          "Editing an agent's goal, tools and budget from this screen",
        ],
        keywords: ["agents", "sdr", "bots"],
      },
      {
        key: "agent-activity",
        label: "Agent Activity",
        href: "/agent-activity",
        icon: Activity,
        status: "live",
        phase: "Phase 8",
        purpose: "Every automated action, timestamped and traceable.",
        planned: [
          "Replaying a run to see the reasoning behind each action",
        ],
        keywords: ["logs", "runs", "audit ai"],
      },
      {
        key: "knowledge-base",
        label: "Knowledge Base",
        href: "/knowledge-base",
        icon: Database,
        status: "live",
        phase: "Phase 6",
        purpose: "What you actually sell, so AI never invents a capability you don't have.",
        planned: [
          "Retrieval-backed grounding — needs drafting wired to a model first",
          "Attaching a file to an entry rather than writing the body inline",
        ],
        keywords: ["kb", "docs", "case studies", "collateral"],
      },
    ],
  },
  {
    key: "admin",
    label: "Admin & Support",
    items: [
      {
        key: "account",
        label: "Account",
        href: "/settings/account",
        icon: BadgeCheck,
        status: "live",
        phase: "Phase 1",
        purpose: "Your profile, password, language and session management.",
        keywords: ["profile", "me", "password"],
      },
      {
        key: "workspace-settings",
        label: "Workspace",
        href: "/settings/workspace",
        icon: Briefcase,
        status: "live",
        phase: "Phase 1",
        purpose: "Company details, currency, timezone, GSTIN and retention defaults.",
        planned: [
          "Uploading a logo, which would appear on proposals",
          "Transferring ownership of the workspace",
        ],
        keywords: ["company", "org", "settings"],
      },
      {
        key: "icp",
        label: "ICP",
        href: "/settings/icp",
        icon: Crosshair,
        status: "live",
        phase: "Phase 2",
        purpose: "Define who you sell to. Everything downstream scores against this.",
        keywords: ["ideal customer", "targeting", "fit"],
      },
      {
        key: "offerings",
        label: "Offerings",
        href: "/settings/offerings",
        icon: Crosshair,
        status: "live",
        phase: "Opportunity intelligence",
        purpose: "Describe what you sell so discovery asks each platform the right way: buyer phrases, job titles and business categories.",
        keywords: ["offering", "products", "services", "discovery", "phrases", "routing"],
      },
      {
        key: "team-roles",
        label: "Team & Roles",
        href: "/settings/team",
        icon: ShieldCheck,
        status: "live",
        phase: "Phase 1",
        purpose: "Members, roles and the exact permissions each role grants.",
        keywords: ["users", "rbac", "permissions", "invite"],
      },
      {
        key: "proposal-setup",
        label: "Proposal Setup",
        href: "/settings/proposals",
        icon: FileText,
        status: "live",
        phase: "Phase 7",
        purpose: "Branding, default terms, tax rates and reusable proposal sections.",
        planned: [
          "Editable workspace defaults — today each proposal carries its own terms",
          "A reusable template library",
        ],
        keywords: ["templates", "branding", "terms"],
      },
      {
        key: "billing",
        label: "Billing & Points",
        href: "/settings/billing",
        icon: CreditCard,
        status: "live",
        phase: "Phase 1",
        purpose: "Plan, seats, point balance and the full immutable transaction ledger.",
        keywords: ["credits", "points", "plan", "invoice", "subscription"],
      },
      {
        key: "search-phrases",
        label: "Search Phrases",
        href: "/settings/search-phrases",
        icon: Filter,
        status: "live",
        phase: "Phase 5",
        purpose: "The queries that feed your radar, with per-phrase quality and revenue.",
        keywords: ["queries", "phrases", "sources"],
      },
      {
        key: "notifications-settings",
        label: "Notifications",
        href: "/settings/notifications",
        icon: Bell,
        status: "live",
        phase: "Phase 1",
        purpose: "Per-type, per-channel notification control.",
        planned: [
          "Push and WhatsApp delivery — notifications arrive in the app and by email only",
        ],
        keywords: ["alerts", "email prefs", "push"],
      },
      {
        key: "email-accounts",
        label: "Email Accounts",
        href: "/settings/email",
        icon: Mail,
        status: "live",
        phase: "Phase 4",
        purpose: "Sending identities, reply readback and domain authentication.",
        planned: [
          "Automated SPF, DKIM and DMARC checking against your live DNS",
          "Per-mailbox daily throttles",
        ],
        keywords: ["smtp", "mailbox", "sending", "spf", "dkim"],
      },
      {
        key: "linkedin-settings",
        label: "LinkedIn",
        href: "/settings/linkedin",
        icon: Contact,
        status: "live",
        phase: "Phase 4",
        purpose: "The scope of what the assisted workflow may do, and what it never will.",
        keywords: ["li settings"],
      },
      {
        key: "whatsapp-settings",
        label: "WhatsApp",
        href: "/settings/whatsapp",
        icon: MessageCircle,
        status: "live",
        phase: "Phase 4",
        purpose: "Number registration, templates and consent defaults.",
        keywords: ["wa settings"],
      },
      {
        key: "whatsapp-api",
        label: "WhatsApp API",
        href: "/settings/whatsapp-api",
        icon: Link2,
        status: "live",
        phase: "Phase 4",
        purpose: "Official Business API credentials, webhooks and template sync.",
        keywords: ["meta", "business api", "cloud api"],
      },
      {
        key: "calendar",
        label: "Calendar",
        href: "/settings/calendar",
        icon: CalendarDays,
        status: "live",
        phase: "Phase 7",
        purpose: "Calendar connections and your scheduling link.",
        planned: [
          "CalDAV calendars (iCloud, Fastmail, self-hosted) — Google and Microsoft 365 are supported",
        ],
        keywords: ["google calendar", "outlook", "cal.com", "calendly"],
      },
      {
        key: "crm-integrations",
        label: "CRM Integrations",
        href: "/settings/integrations",
        icon: Network,
        status: "live",
        phase: "Phase 9",
        purpose: "Two-way sync with the CRM you already run on.",
        keywords: ["hubspot", "salesforce", "zoho", "sync"],
      },
      {
        key: "ai-assistant",
        label: "AI Assistant",
        href: "/settings/ai",
        icon: Sparkles,
        status: "live",
        phase: "Phase 6",
        purpose: "Model routing, provider status and what AI has actually cost.",
        planned: [
          "OpenAI and Gemini adapters — both are routed, only Anthropic is built",
          "Per-workspace spend caps, and a tone default applied to drafting",
        ],
        keywords: ["models", "providers", "llm", "tone"],
      },
      {
        key: "mcp",
        label: "MCP",
        href: "/settings/mcp",
        icon: Zap,
        status: "live",
        phase: "Phase 9",
        purpose: "Operate this workspace from Claude, Claude Code, Cursor and other MCP clients.",
        planned: [
          "OAuth device flow, so a client can connect without pasting a key",
        ],
        keywords: ["model context protocol", "claude", "cursor", "tools"],
      },
      { key: "providers", label: "Lead Sources & APIs", href: "/settings/providers", icon: Database, status: "live", phase: "Opportunity intelligence", purpose: "Connect discovery and contact APIs, configure job boards, and check worker readiness.", keywords: ["brave", "signalhire", "adzuna", "hunter", "sources", "api", "workers"] },
      {
        key: "api-keys",
        label: "API Keys",
        href: "/settings/api-keys",
        icon: KeyRound,
        status: "live",
        phase: "Phase 9",
        purpose: "Named, scoped, expirable keys. Shown once, never again.",
        keywords: ["tokens", "secrets", "api"],
      },
      {
        key: "webhooks",
        label: "Webhooks",
        href: "/settings/webhooks",
        icon: Webhook,
        status: "live",
        phase: "Phase 9",
        purpose: "Signed event delivery with retries and a delivery log.",
        keywords: ["events", "callbacks", "hooks"],
      },
      {
        key: "data-privacy",
        label: "Data & Privacy",
        href: "/settings/privacy",
        icon: ShieldCheck,
        status: "live",
        phase: "Phase 10",
        purpose: "Consent, suppression, export, deletion and retention — the operational controls, not a badge.",
        planned: [
          "Self-serve export of one person's data as a file",
          "A verified erasure request flow",
        ],
        keywords: ["dpdp", "gdpr", "consent", "suppression", "compliance"],
      },
      {
        key: "jobs",
        label: "Workers & Background Jobs",
        href: "/settings/jobs",
        icon: Workflow,
        status: "live",
        phase: "Phase 10",
        purpose: "Queue health, recurring schedules, recent runs and what each one changed.",
        keywords: ["queue", "worker", "cron", "bullmq", "redis", "scheduled"],
      },
      {
        key: "audit-log",
        label: "Audit Log",
        href: "/settings/audit",
        icon: ScrollText,
        status: "live",
        phase: "Phase 1",
        purpose: "Who did what, when, from where — including AI and API actors.",
        keywords: ["history", "trail", "compliance"],
      },
      {
        key: "archived-leads",
        label: "Archived Leads",
        href: "/archived",
        icon: Archive,
        status: "live",
        phase: "Phase 2",
        purpose: "Leads auto-archived after inactivity, still fully searchable.",
        planned: [
          "Bulk restore and bulk discard from this screen",
        ],
        keywords: ["archive", "dormant", "cold storage"],
      },
      {
        key: "recycle-bin",
        label: "Recycle Bin",
        href: "/recycle-bin",
        icon: Trash2,
        status: "live",
        phase: "Phase 10",
        purpose: "Soft-deleted records with restore and a visible purge date.",
        planned: [
          "Restoring a proposal, booking or deal — those are recorded but not yet restorable",
          "Purging an item early, before its retention date",
        ],
        keywords: ["trash", "deleted", "restore"],
      },
      {
        key: "approvals",
        label: "Approval Center",
        href: "/approvals",
        icon: ClipboardCheck,
        status: "live",
        phase: "Phase 8",
        purpose: "One queue for every AI action waiting on a human.",
        planned: [
          "Approving research and proposal drafts, once those agents can run",
        ],
        counter: "approvals",
        keywords: ["approve", "review", "queue ai"],
      },
      {
        key: "trust-center",
        label: "Trust Center",
        href: "/trust",
        icon: ShieldCheck,
        status: "live",
        phase: "Phase 8",
        purpose: "Exactly what automation is allowed to do, in one screen.",
        planned: [
          "An exportable record of every automated action, for audit",
        ],
        keywords: ["safety", "limits", "permissions ai"],
      },
      {
        key: "whats-new",
        label: "What's New",
        href: "/whats-new",
        icon: AlarmClock,
        status: "live",
        phase: "Phase 10",
        purpose: "Release notes for the workspace.",
        planned: [
          "Marking entries as read, so only what changed since your last visit is highlighted",
        ],
        keywords: ["changelog", "updates", "releases"],
      },
      {
        key: "support",
        label: "Support",
        href: "/support",
        icon: LifeBuoy,
        status: "live",
        phase: "Phase 10",
        purpose: "Get help, report a problem, see system status.",
        planned: [
          "In-app ticketing — nothing here opens a case, and nothing pretends to",
        ],
        keywords: ["help", "contact", "docs"],
      },
      {
        key: "settings-root",
        label: "All settings",
        href: "/settings",
        icon: Settings,
        status: "live",
        phase: "Phase 1",
        purpose: "Index of every workspace and account setting.",
        keywords: ["preferences", "config"],
      },
    ],
  },
];

export const ALL_NAV_ITEMS: NavItem[] = NAV.flatMap((g) => g.items);

export function findNavItem(pathname: string): NavItem | undefined {
  // Longest matching href wins so /settings/billing beats /settings.
  return [...ALL_NAV_ITEMS]
    .sort((a, b) => b.href.length - a.href.length)
    .find((i) => pathname === i.href || pathname.startsWith(`${i.href}/`));
}

export function navItemByKey(key: string): NavItem | undefined {
  return ALL_NAV_ITEMS.find((i) => i.key === key);
}
