import Link from "next/link";
import { requireAuth } from "@/lib/auth/context";
import { opportunityTypes } from "@/lib/opportunities/query-parser";
import { listOpportunities } from "@/lib/services/opportunities";
import { OpportunityTable } from "@/components/opportunities/table";
export const metadata = { title: "Opportunities" };
export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const ctx = await requireAuth(); const params = await searchParams; const data = await listOpportunities(ctx, params);
  return <div className="space-y-6 p-6"><div className="flex justify-between"><h1 className="text-2xl font-semibold">Opportunities</h1><div className="flex gap-4"><Link href="/opportunities/review" className="underline">Discovery review</Link><Link href="/find-leads" className="underline">Find opportunities</Link></div></div><form className="flex flex-wrap gap-3"><input aria-label="Search opportunities" name="q" placeholder="Service or company" defaultValue={params.q} className="rounded border border-border bg-surface p-2" /><input aria-label="Minimum intent" name="intent" type="number" min="0" max="100" placeholder="Minimum intent" defaultValue={params.intent} className="rounded border border-border bg-surface p-2" /><select aria-label="Posting date" name="days" defaultValue={params.days ?? ""} className="rounded border border-border bg-surface p-2"><option value="">Any posting date</option><option value="3">Last 3 days</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><select name="type" aria-label="Opportunity type" defaultValue={params.type ?? ""} className="rounded border border-border bg-surface p-2"><option value="">All opportunity types</option>{opportunityTypes.map(t=><option key={t} value={t}>{t.replaceAll("_"," ")}</option>)}</select><select name="source" aria-label="Source" defaultValue={params.source ?? ""} className="rounded border border-border bg-surface p-2"><option value="">All sources</option>{["brave","greenhouse","lever","ashby","adzuna"].map(p=><option key={p}>{p}</option>)}</select><select name="status" aria-label="Status" defaultValue={params.status ?? ""} className="rounded border border-border bg-surface p-2"><option value="">All statuses</option>{["ACTIVE","OPEN","CLOSED","EXPIRED","UNKNOWN"].map(p=><option key={p}>{p}</option>)}</select><input name="location" aria-label="Location" placeholder="Location" defaultValue={params.location} className="rounded border border-border bg-surface p-2" /><input name="technology" aria-label="Technology" placeholder="Technology" defaultValue={params.technology} className="rounded border border-border bg-surface p-2" /><button className="rounded border border-border px-4">Filter</button><Link href="/opportunities" className="self-center underline">Clear</Link></form><a href={`/api/opportunities/export?${new URLSearchParams(params)}`} className="inline-block text-sm underline">Export this page as CSV (permitted sources only)</a><OpportunityTable data={data} />{data.total > data.page * 50 && <Link href={`/opportunities?${new URLSearchParams({ ...params, page: String(data.page + 1) })}`}>Next page</Link>}</div>;
}
