"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { api } from "@/lib/api/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { listOpportunityProviders, getDiscoveryReadiness } from "@/lib/services/opportunity-providers";
type Board = { slug: string; company: string; domain: string; country?: string };
type Config = { boards?: Board[]; appId?: string; countries?: string[]; maxQueries?: number; pages?: number; includeLinkedIn?: boolean };
export function ProviderSettings({ providers, readiness, canManage }: { providers: Awaited<ReturnType<typeof listOpportunityProviders>>; readiness: Awaited<ReturnType<typeof getDiscoveryReadiness>>; canManage: boolean }) {
  const router = useRouter(); const [selected, setSelected] = useState("brave"); const [key, setKey] = useState(""); const [boards, setBoards] = useState<Board[]>([]); const [rights, setRights] = useState(false); const [exportAllowed, setExportAllowed] = useState(false); const [enabled, setEnabled] = useState(true); const [retention, setRetention] = useState(30); const [appId, setAppId] = useState(""); const [countries, setCountries] = useState(["us", "gb", "in"]); const [maxQueries, setMaxQueries] = useState(3); const [pages, setPages] = useState(1); const [includeLinkedIn, setIncludeLinkedIn] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const descriptor = providers.find(p => p.id === selected)!;
  const isBoard = ["greenhouse", "lever", "ashby"].includes(selected);
  function choose(id: string) { const p = providers.find(p => p.id === id); const c = (p?.connection?.config ?? {}) as Config; setSelected(id); setKey(""); setBoards(c.boards ?? []); setAppId(c.appId ?? ""); setCountries(c.countries ?? ["us", "gb", "in"]); setMaxQueries(c.maxQueries ?? 3); setPages(c.pages ?? 1); setIncludeLinkedIn(c.includeLinkedIn ?? true); setRights(Boolean(p?.connection?.allowedStorage)); setExportAllowed(Boolean(p?.connection?.allowedExport)); setRetention(p?.connection?.retentionDays ?? 30); setEnabled(p?.connection?.enabled ?? true); }
  async function save() { setBusy(true); setMessage(""); try { await api.post(`/api/providers/${selected}/connect`, { apiKey: key || undefined, enabled, retentionDays: retention, config: { boards, appId, countries, maxQueries, pages, includeLinkedIn }, allowedSearch: rights, allowedStorage: rights, allowedEnrichment: rights, allowedExport: exportAllowed }); setKey(""); setMessage("Connection saved. Test API access, then run a discovery search."); router.refresh(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not save connection."); } finally { setBusy(false); } }
  async function test(id: string) { setBusy(true); try { const r = await api.post<{ message: string }>(`/api/providers/${id}/test`, {}); setMessage(r.message); router.refresh(); } catch(e) { setMessage(e instanceof Error ? e.message : "Test failed."); } finally { setBusy(false); } }
  return <div className="space-y-6">
    <section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Discovery readiness</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><p>API key encryption<br /><strong className="text-sm">{readiness.encryptionConfigured ? "Ready" : "Server setup required"}</strong></p><p>Queue / Redis<br /><strong className="text-sm">{readiness.queue.reachable ? "Connected" : readiness.queue.configured ? "Unreachable" : "Not configured"}</strong></p><p>Workers<br /><strong className="text-sm">{readiness.queue.workers === null ? "Cannot check" : `${readiness.queue.workers} connected`}</strong></p></div><div className="mt-4 flex flex-wrap gap-4 text-sm underline"><Link href="/settings/jobs">Workers & background jobs</Link><Link href="/find-leads">Find opportunities</Link><Link href="/opportunities/review">Review web & LinkedIn matches</Link><Link href="/settings/api-keys">Signalroom API keys</Link><button onClick={() => router.refresh()}>Refresh status</button></div><details className="mt-4 text-sm text-secondary"><summary>Server setup instructions</summary><p className="mt-2">Configure REDIS_URL and a stable 64-character hexadecimal PROVIDER_ENCRYPTION_KEY in the server environment. Start or restart the worker with <code>npm run worker</code> after deploying updates. Worker processes run on your server; this page reports their connections.</p><p className="mt-2">Provider API keys below connect external lead sources. Signalroom API keys let other applications access this workspace.</p></details></section>
    {message && <p role="status" className="rounded border border-border p-3 text-sm">{message}</p>}
    <div className="grid gap-3 md:grid-cols-2">{providers.map(p => <article key={p.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">{p.name}</h2><span className="text-xs text-secondary">{p.connection?.enabled === false ? "Disabled" : p.connection?.status ?? (p.implemented ? "Not connected" : "Unavailable")}</span></div><p className="mt-2 text-sm text-secondary">{p.description}</p>{canManage && p.implemented && <div className="mt-3 flex gap-2"><Button variant="outline" disabled={busy} onClick={() => { choose(p.id); document.getElementById("provider-form")?.scrollIntoView({ behavior: "smooth" }); }}>{p.connection ? "Edit connection" : "Configure"}</Button>{p.connection && <Button variant="outline" disabled={busy} onClick={() => test(p.id)}>Test API access</Button>}</div>}</article>)}</div>
    {canManage && <form id="provider-form" onSubmit={e => {e.preventDefault(); void save();}} className="space-y-4 rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Configure {descriptor.name}</h2><label className="block text-sm">Provider<select className="ml-3 rounded border border-border bg-surface p-2" value={selected} onChange={e => choose(e.target.value)}>{providers.filter(p => p.implemented).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    {descriptor.key && <label className="block text-sm">Provider API key<Input type="password" autoComplete="new-password" value={key} onChange={e => setKey(e.target.value)} placeholder={descriptor.connection ? "Leave blank to keep the saved key" : "Paste your provider key"} /><span className="text-xs text-secondary">Encrypted on the server; never returned to this page.</span></label>}
    {selected === "adzuna" && <><label className="block text-sm">Adzuna application ID<Input required value={appId} onChange={e => setAppId(e.target.value)} /></label><fieldset className="flex flex-wrap gap-3"><legend className="mb-2 text-sm">Job markets</legend>{["us","gb","in","au","at","br","ca","de","fr","it","nl","nz","pl","sg","za"].map(c => <label key={c} className="text-sm"><input type="checkbox" checked={countries.includes(c)} onChange={e => setCountries(e.target.checked ? [...countries,c] : countries.filter(v => v !== c))} /> {c.toUpperCase()}</label>)}</fieldset><label className="block text-sm">Pages per query / country<select value={pages} onChange={e => setPages(Number(e.target.value))} className="ml-3 rounded border border-border bg-surface p-2">{[1,2,3].map(n => <option key={n} value={n}>{n} (up to {n*50} jobs)</option>)}</select></label></>}
    {["brave", "adzuna"].includes(selected) && <label className="block text-sm">Query variants per search<select value={maxQueries} onChange={e => setMaxQueries(Number(e.target.value))} className="ml-3 rounded border border-border bg-surface p-2">{[1,2,3,4,5,6].map(n => <option key={n} value={n}>{n}</option>)}</select><p className="mt-1 text-xs text-secondary">Broader coverage uses more provider requests. Shared limits apply: 20/minute, 300/hour and 1,500/day.</p></label>}
    {selected === "brave" && <label className="block text-sm"><input type="checkbox" checked={includeLinkedIn} onChange={e => setIncludeLinkedIn(e.target.checked)} /> Include indexed public LinkedIn posts (up to two additional searches)</label>}
    {(isBoard || selected === "brave") && <fieldset className="space-y-3"><legend className="text-sm font-medium">{isBoard ? "Company job boards" : "Known company domains (optional)"}</legend><p className="text-xs text-secondary">{isBoard ? "Add the board slug from the company's hosted careers URL, its name and confirmed website domain." : "Search works without a company list. Known domains allow automatic company attribution; other matches enter discovery review."}</p>{boards.map((b,i) => <div key={i} className="grid gap-2 sm:grid-cols-5">{(["slug","company","domain","country"] as const).map(field => <Input key={field} aria-label={`Board ${i+1} ${field}`} placeholder={field} value={b[field] ?? ""} required={field !== "country"} onChange={e => setBoards(boards.map((row,j) => j === i ? {...row,[field]:e.target.value} : row))} />)}<Button variant="outline" type="button" onClick={() => setBoards(boards.filter((_,j) => j !== i))}>Remove</Button></div>)}<Button type="button" variant="outline" onClick={() => setBoards([...boards,{slug:"",company:"",domain:""}])}>Add company board</Button></fieldset>}
    <label className="block text-sm">Retention days<Input type="number" min={1} max={365} value={retention} onChange={e => setRetention(Number(e.target.value))} className="mt-1 max-w-32" /></label><label className="block text-sm"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /> Enable this connection</label><label className="block text-sm"><input type="checkbox" checked={rights} onChange={e => setRights(e.target.checked)} required={enabled} /> My provider licence permits these searches and storage for {retention} days.</label><label className="block text-sm"><input type="checkbox" checked={exportAllowed} onChange={e => setExportAllowed(e.target.checked)} /> My provider licence permits exporting results.</label><Button disabled={busy || (enabled && !rights) || (descriptor.key && !readiness.encryptionConfigured)}>Save connection</Button></form>}
    <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Recent provider activity</h2>{readiness.recent.length ? <div className="mt-3 space-y-2">{readiness.recent.map(r => <p key={r.id} className="text-sm"><strong>{r.provider}</strong> · {r.operation.replaceAll("_", " ")} · {r.state} · {r.recordsFound} records{r.error ? ` · ${r.error}` : ""}</p>)}</div> : <p className="mt-2 text-sm text-secondary">No provider requests recorded yet.</p>}</section><p className="text-xs text-secondary">API tests and discovery may consume provider quota. No Signalroom points are currently charged. Credentials are needed for a live search; connecting an API does not guarantee a particular number of leads.</p>
  </div>;
}
