import type { SearchCriteria } from "@/lib/opportunities/query-parser";
import type { SourceDocument } from "@/lib/opportunities/extractor";
export type ProviderCapabilities = { search: boolean; enrichment: boolean; verification: boolean; changes: boolean; limitation?: string };
export interface OpportunitySourceProvider {
  id: string;
  search(query: SearchCriteria): Promise<SourceDocument[]>;
  getOpportunity(id: string): Promise<SourceDocument | null>;
  getChanges(id: string): Promise<SourceDocument | null>;
  healthCheck(): Promise<{ ok: boolean; message: string }>;
  getCapabilities(): ProviderCapabilities;
}
export const PROVIDERS = [
  { id: "brave", name: "Brave Public Web", kind: "PUBLIC_WEB", implemented: true, key: true, description: "Commercial search API. Storage requires a licence permitting retention. Searches the open web with buyer-phrased queries. A result is kept only when a buyer can be named: the page owner making its own request, or an organisation named in the text and checked word for word. Search indexes do not reach LinkedIn posts." },
  { id: "linkedin_posts", name: "LinkedIn posts (via Apify)", kind: "LINKEDIN", implemented: true, key: true, description: "Searches public LinkedIn posts through a third-party Apify scraper (apimaestro/linkedin-posts-search-scraper-no-cookies) with your Apify API token. This is not a LinkedIn API: scraping is against LinkedIn's User Agreement, and enabling it means your workspace accepts that risk. Apify bills your account for each post returned, capped per search by the ceiling you set here. A post qualifies automatically only when the buyer organisation is named in it; relevant buying posts without a named buyer, or with unknown company details, are kept for review." },
  { id: "apify_linkedin_jobs", name: "LinkedIn jobs (via Apify)", kind: "JOB_BOARD", implemented: true, key: true, description: "LinkedIn job postings through the curious_coder/linkedin-jobs-scraper Actor (no cookies), on your Apify token. A job posting is internal hiring, never proof the company wants a vendor. $0.002 per job at Apify's FREE-tier price, capped per search by the limit set here. Scraping LinkedIn is against its User Agreement; enabling this means your workspace accepts that risk." },
  { id: "apify_indeed", name: "Indeed (via Apify)", kind: "JOB_BOARD", implemented: true, key: true, description: "Indeed job postings through the valig/indeed-jobs-scraper Actor, on your Apify token. Filters by posting date up to 14 days; longer windows run unfiltered and are checked here. Internal hiring, not vendor demand. About $0.0001 per job plus $0.001 per run (FREE tier)." },
  { id: "apify_naukri", name: "Naukri (via Apify)", kind: "JOB_BOARD", implemented: true, key: true, description: "Naukri.com job postings through the muhammetakkurtt/naukri-job-scraper Actor, on your Apify token. Internal hiring, not vendor demand. $0.0015 per job plus $0.001 per run (FREE tier)." },
  { id: "apify_google_search", name: "Google Search (via Apify)", kind: "PUBLIC_WEB", implemented: true, key: true, description: "Google results for buyer-phrased queries through apify/google-search-scraper, on your Apify token. A page is kept only when a buyer can be named, as for Brave. $0.0045 per results page plus $0.001 per run (FREE tier)." },
  { id: "apify_reddit", name: "Reddit (via Apify)", kind: "SOCIAL", implemented: true, key: true, description: "Public Reddit posts through trudax/reddit-scraper-lite, on your Apify token. Posts only, NSFW excluded. A username is not a company: a post is kept only when a buyer is named in it, otherwise it is screened out with the reason. $0.004 per post plus $0.02 per run (FREE tier)." },
  { id: "apify_upwork", name: "Upwork (via Apify)", kind: "MARKETPLACE", implemented: true, key: true, description: "Upwork job posts — direct requests for an outside provider — through neatrat/upwork-job-scraper, on your Apify token, without cookies. Upwork hides most client names; a post without a confidently named client is screened, not guessed. About $0.0035 per job (FREE tier); whether both listed per-job events are charged is unconfirmed, so estimates assume both." },
  { id: "apify_google_maps", name: "Google Maps businesses (via Apify)", kind: "BUSINESS_LISTING", implemented: true, key: true, description: "Businesses listed on Google Maps for categories and an area you set, through compass/crawler-google-places, on your Apify token. Saved as company prospects with category, location and published phone — fit evidence only, never an opportunity or intent. $0.004 per place (FREE tier); contact scraping is not requested." },
  { id: "apify_websites", name: "Public websites (via Apify)", kind: "COMPANY_SITE", implemented: true, key: true, description: "Reads the public pages you list (for example a procurement or tenders page) through apify/website-content-crawler, respecting robots.txt, capped at the pages set here. A page is kept only when it names a buyer. Billed as Apify compute." },
  { id: "greenhouse", name: "Greenhouse", kind: "JOB_BOARD", implemented: true, key: false, description: "Public Job Board API for explicitly configured company boards. Posting dates may be unavailable." },
  { id: "lever", name: "Lever", kind: "JOB_BOARD", implemented: true, key: false, description: "Public postings API for explicitly configured company boards." },
  { id: "ashby", name: "Ashby", kind: "JOB_BOARD", implemented: true, key: false, description: "Public job postings from configured Ashby company boards." },
  { id: "adzuna", name: "Adzuna Jobs", kind: "JOB_BOARD", implemented: true, key: true, description: "Discover hiring companies across supported country job markets without a company list. Requires your app ID and API key." },
  { id: "signalhire", name: "SignalHire", kind: "CONTACT", implemented: true, key: true, description: "Work emails for a person's LinkedIn profile through the Person API, used by the contact-provider fallback after Apify. SignalHire's full lookup delivers results only to a public callback URL, so this app uses its synchronous mode, which reads SignalHire's stored data and finds fewer contacts. Charged per successful match." },
  { id: "apify_enrichment", name: "Apify enrichment", kind: "CONTACT", implemented: true, key: true, description: "Researches an opportunity's company, finds relevant people and business emails, and checks those emails — all through Apify Actors, on the Apify token already saved for LinkedIn posts (or one entered here). No Hunter, SignalHire or other key is needed. Actors: Google Search Results Scraper, HarvestAPI LinkedIn Company and Company Employees, Website Contact Finder and BounceVerify; each is billed to your Apify account per result, within the per-run budget set here. Scraping LinkedIn is against LinkedIn's User Agreement; enabling this means your workspace accepts that risk." },
  { id: "hunter", name: "Hunter", kind: "CONTACT", implemented: true, key: true, description: "Domain contact discovery and email verification through your licensed Hunter account." },
  { id: "linkedin", name: "LinkedIn / Sales Navigator", kind: "LINKEDIN", implemented: false, key: false, description: "LinkedIn capability unavailable for this connection. Generic member OAuth does not grant prospect search. A partner-approved integration is required." },
  { id: "apollo", name: "Apollo", kind: "CONTACT", implemented: true, key: true, description: "People Enrichment through your Apollo API key, used by the contact-provider fallback after Apify for people still without a company email. Each match can spend one Apollo credit; personal emails and phone numbers are never requested. Needs enrichment and storage rights." },
  { id: "company_site", name: "Company websites", kind: "COMPANY_SITE", implemented: false, key: false, description: "Direct crawling is disabled. Use configured public career feeds; a robots-aware, terms-approved crawler is not connected." },
  { id: "news", name: "News / press", kind: "NEWS", implemented: false, key: true, description: "No licensed news adapter connected." },
  { id: "rfp", name: "Public procurement", kind: "RFP", implemented: false, key: true, description: "No procurement adapter connected." },
] as const;
export type ProviderId = typeof PROVIDERS[number]["id"];

export const DISCOVERY_PROVIDERS = ["brave", "linkedin_posts", "greenhouse", "lever", "ashby", "adzuna", "apify_linkedin_jobs", "apify_indeed", "apify_naukri", "apify_google_search", "apify_reddit", "apify_upwork", "apify_google_maps", "apify_websites"] as const;

export class PartialDiscoveryError extends Error {
  constructor(message: string, public readonly documents: SourceDocument[]) { super(message); }
}
